#!/bin/bash
# chkconfig: 2345 90 10
# description: A secure socks5 proxy, designed to protect your Internet traffic.

### BEGIN INIT INFO
# Provides:          ShadowsocksR
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Fast tunnel proxy that helps you bypass firewalls
# Description:       Start or stop the ShadowsocksR server
### END INIT INFO

# Author: Teddysun <i@teddysun.com>

NAME=ShadowsocksR
BIN=/usr/local/shadowsocksr/shadowsocks/server.py
CONF=/etc/shadowsocksr.json
RETVAL=0

check_running(){
    PID=$(ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}')
    if [[ -n "${PID}" ]]; then
        return 0
    else
        return 1
    fi
}

do_start(){
    if check_running; then
        echo "$NAME (pid $PID) is already running..."
        RETVAL=0
        exit 0
    else
        if $BIN -c $CONF -d start; then
            echo "Starting $NAME success"
            RETVAL=0
        else
            echo "Starting $NAME failed"
            RETVAL=1
        fi
    fi
}

do_stop(){
    if check_running; then
        if $BIN -c $CONF -d stop; then
            echo "Stopping $NAME success"
            RETVAL=0
        else
            echo "Stopping $NAME failed"
            RETVAL=1
        fi
    else
        echo "$NAME is stopped"
        RETVAL=1
    fi
}

do_status(){
    if check_running; then
        echo "$NAME (pid $PID) is running..."
    else
        echo "$NAME is stopped"
        RETVAL=1
    fi
}

do_restart(){
    do_stop
    sleep 0.5
    do_start
}

case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    echo "Usage: $0 { start | stop | restart | status }"
    RETVAL=1
    ;;
esac

exit $RETVAL
